services:
  - type: web
    name: coplate-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 1000
      - key: PYTHONUNBUFFERED
        value: 1
